### ISSUE TITLE
`Shift + Click` opens video in a new window on youtube itself

### ISSUE THREAD

**Issue by blemasle** [d3vr/yt-siphon#3]
As stated [here](https://support.mozilla.org/en-US/kb/mouse-shortcuts-perform-common-tasks#w_links), `Shift + Click` is the default Firefox shortcut to open a link in a new window.

`Alt + J` is therefore the only option to use this extension, at least on my browser. Though I'm surprised no one nor you has encountered this issue before.

As a side note, a context menu entry to "Open link in a new siphon tab" or similar might be a very good idea to directly open links embedded on external websites with youtube siphon. See [here](https://github.com/blemasle/youtube-uncookify/blob/main/src/uncookify.js#L71) for instance (disclaimer : I'm the author of this extension which I can gladly retire now that I discovered yours on HN 😁)

**Comment by d3vr** [comment]
This add-on actually overrides that behavior when you're on  a YouTube page. Like shown in the README, you have to enable permissions for the add-on to run on YouTube and once you've done that, refresh the page so that the content script is actually injected into a YouTube page.
Maybe I should add an instructions page that shows up once the add-on has been installed to clarify this 🤔

> As a side note, a context menu entry to "Open link in a new siphon tab" or similar might be a very good idea

That is indeed a good idea, will look into it.

**Comment by blemasle** [comment]
🤦Ahh I missed that part, sorry. I should have RTFM until the end...

**Comment by sashablue** [comment]
OK, Shift+Click works after:
While youtube tab is active, in the addon setting, **Always allow on www.youtube.com** should be ticked.
![image](https://github.com/d3vr/yt-siphon/assets/16237152/1fe5595b-bcf4-4ee1-bcad-44903aa93c74)
Thanks for your reply d3vr
